config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'errors/error_404'
  get 'errors/error_505'
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  delete 'logout' => 'session#destroy'
  get '/auth/:provider/callback' => 'session#create'
  resources :users
  resources :posts do
    resources :comments
    resource :likes
  end
  resource :comments do
    resource :comments
  end

  match '*not_found' => 'errors#error_404', via: :all
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id               :bigint           not null, primary key
#  body             :text
#  commentable_type :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  comment_id       :bigint
#  commentable_id   :integer
#  user_id          :bigint           not null
#
# Indexes
#
#  index_comments_on_comment_id  (comment_id)
#  index_comments_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (comment_id => comments.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true

  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :logged?, only: %i[create destroy]
  before_action :correct_user, only: :destroy
  before_action :find_commentable, only: :create

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = 'Commented!'
      redirect_to request.referrer
    else
      redirect_to request.referrer || root_path
      flash[:warning] = @comment.errors.full_messages.to_sentence
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'Comment deleted'
    redirect_to request.referrer || current_user
  end

  private

  def correct_user
    @comment = current_user.posts.comments.find(params[:id])
    redirect_to root_path if @comment.blank?
    flash[:warning] = 'It is not your comment'
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    @commentable = Comment.find(params[:format]) if params[:format]
    @commentable = Post.find(params[:post_id]) if params[:post_id]
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="comment">
  <%= comment.body %> -
  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>
  <%= form_for :comment, url: comments_comments_path(comment) do |f| %>
    <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
    <%= f.submit "Reply"  %>
  <% end %>

  <ul>
    <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/comments/_comment_form.html.erb
<%= form_for :comment, url: posts_path do |f| %>
  <div class="field">
    <%= f.text_area :body, placeholder: "...new comment..." %>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>